export const education = [{
      id: 1,
      img: "/images/uni.png",
      school: "Kalinga Institute of Industrial Technology, Bhubaneswar",
      date: "July 2023 - Present",
      grade: "8.60(Till 4th semester)",
      desc: "I am pursuing my Bachelor's degree in Computer Science and Engineering (BTech CSE) at KIIT University, Bhubaneswar. Throughout my studies, I immerse myself in a variety of subjects that deepen my understanding of computing and technology. From exploring Data Structures and Algorithms to diving into Web Development and Database Management Systems, I gain practical insights into the world of software development. My time at KIIT University allows me to work on projects that apply theoretical concepts to real-world problems.",
      degree: "BTech CSE",
    },
    {
      id: 2,
      img: "/images/school.jpg",
      school: "Satish Chandra Memorial School, Chakdaha",
      date: "Apr 2022 - March 2023",
      grade: "75%",
      desc: "I completed my class 12 education from Satish Chandra Memorial School, Chakdaha, under the CBSE board, where I studied Physics, Chemistry, Mathematics and Biology (PCMB).",
      degree: "CBSE(XII), PCMB",
    },
    {
      id: 3,
      img: "/images/school.jpg",
      school: "Satish Chandra Memorial School, Chakdaha",
      date: "Apr 2020 - March 2021",
      grade: "84%",
      desc: "I completed my class 10 education from Satish Chandra Memorial School, Chakdaha, under the CBSE board, where I studied Science.",
      degree: "CBSE(X), Science",
    },
  ];